spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: TravelTo
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: ${DB_DRIVER}
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

server:
    port: ${SERVER_PORT}

app:
    jwt:
        secret: ${APP_JWT_SECRET}
        expiration-minutes: ${APP_JWT_EXPIRE_MINUTES}
    cors:
        allowed-origins:
            - ${FE_ORIGIN}
    security:
        admin-emails:
            - ${ADMIN_EMAIL}
    google:
        token-info-url: https://oauth2.googleapis.com/tokeninfo
