server:
    port: 8080

spring:
    profiles:
        active: dev
    application:
        name: TravelTo
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

app:
    jwt:
        secret: ${APP_JWT_SECRET}
        expiration-minutes: ${APP_JWT_EXPIRE_MINUTES}
    cors:
        allowed-origins:
            - ${FE_ORIGIN}
    security:
        admin-emails:
            - ${ADMIN_EMAIL}
    google:
        token-info-url: https://oauth2.googleapis.com/tokeninfo
    vnpay:
        version: "2.1.0"
        command: "pay"
        tmn-code: ${VNPAY_TMN_CODE}
        hash-secret: ${VNPAY_HASH_SECRET}
        pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
        return-url: ${VNPAY_RETURN_URL}
